//
// Created by Kim Johannsen on 31-03-2018.
//

#include <Core/Enum.h>
#include "Key.h"

BeginUnit(Key)
    BeginEnum(Key, false)
        RegisterFlag(KEY_NONE)

        RegisterFlag(KEY_SPACE)
        RegisterFlag(KEY_APOSTROPHE)
        RegisterFlag(KEY_COMMA)
        RegisterFlag(KEY_MINUS)
        RegisterFlag(KEY_PERIOD)
        RegisterFlag(KEY_SLASH)
        RegisterFlag(KEY_0)
        RegisterFlag(KEY_1)
        RegisterFlag(KEY_2)
        RegisterFlag(KEY_3)
        RegisterFlag(KEY_4)
        RegisterFlag(KEY_5)
        RegisterFlag(KEY_6)
        RegisterFlag(KEY_7)
        RegisterFlag(KEY_8)
        RegisterFlag(KEY_9)
        RegisterFlag(KEY_SEMICOLON)
        RegisterFlag(KEY_EQUAL)
        RegisterFlag(KEY_A)
        RegisterFlag(KEY_B)
        RegisterFlag(KEY_C)
        RegisterFlag(KEY_D)
        RegisterFlag(KEY_E)
        RegisterFlag(KEY_F)
        RegisterFlag(KEY_G)
        RegisterFlag(KEY_H)
        RegisterFlag(KEY_I)
        RegisterFlag(KEY_J)
        RegisterFlag(KEY_K)
        RegisterFlag(KEY_L)
        RegisterFlag(KEY_M)
        RegisterFlag(KEY_N)
        RegisterFlag(KEY_O)
        RegisterFlag(KEY_P)
        RegisterFlag(KEY_Q)
        RegisterFlag(KEY_R)
        RegisterFlag(KEY_S)
        RegisterFlag(KEY_T)
        RegisterFlag(KEY_U)
        RegisterFlag(KEY_V)
        RegisterFlag(KEY_W)
        RegisterFlag(KEY_X)
        RegisterFlag(KEY_Y)
        RegisterFlag(KEY_Z)
        RegisterFlag(KEY_LEFT_BRACKET)
        RegisterFlag(KEY_BACKSLASH)
        RegisterFlag(KEY_RIGHT_BRACKET)
        RegisterFlag(KEY_GRAVE_ACCENT)
        RegisterFlag(KEY_WORLD_1)
        RegisterFlag(KEY_WORLD_2)
        RegisterFlag(KEY_ESCAPE)
        RegisterFlag(KEY_ENTER)
        RegisterFlag(KEY_TAB)
        RegisterFlag(KEY_BACKSPACE)
        RegisterFlag(KEY_INSERT)
        RegisterFlag(KEY_DELETE)
        RegisterFlag(KEY_RIGHT)
        RegisterFlag(KEY_LEFT)
        RegisterFlag(KEY_DOWN)
        RegisterFlag(KEY_UP)
        RegisterFlag(KEY_PAGE_UP)
        RegisterFlag(KEY_PAGE_DOWN)
        RegisterFlag(KEY_HOME)
        RegisterFlag(KEY_END)
        RegisterFlag(KEY_CAPS_LOCK)
        RegisterFlag(KEY_SCROLL_LOCK)
        RegisterFlag(KEY_NUM_LOCK)
        RegisterFlag(KEY_PRINT_SCREEN)
        RegisterFlag(KEY_PAUSE)
        RegisterFlag(KEY_F1)
        RegisterFlag(KEY_F2)
        RegisterFlag(KEY_F3)
        RegisterFlag(KEY_F4)
        RegisterFlag(KEY_F5)
        RegisterFlag(KEY_F6)
        RegisterFlag(KEY_F7)
        RegisterFlag(KEY_F8)
        RegisterFlag(KEY_F9)
        RegisterFlag(KEY_F10)
        RegisterFlag(KEY_F11)
        RegisterFlag(KEY_F12)
        RegisterFlag(KEY_F13)
        RegisterFlag(KEY_F14)
        RegisterFlag(KEY_F15)
        RegisterFlag(KEY_F16)
        RegisterFlag(KEY_F17)
        RegisterFlag(KEY_F18)
        RegisterFlag(KEY_F19)
        RegisterFlag(KEY_F20)
        RegisterFlag(KEY_F21)
        RegisterFlag(KEY_F22)
        RegisterFlag(KEY_F23)
        RegisterFlag(KEY_F24)
        RegisterFlag(KEY_F25)
        RegisterFlag(KEY_KP_0)
        RegisterFlag(KEY_KP_1)
        RegisterFlag(KEY_KP_2)
        RegisterFlag(KEY_KP_3)
        RegisterFlag(KEY_KP_4)
        RegisterFlag(KEY_KP_5)
        RegisterFlag(KEY_KP_6)
        RegisterFlag(KEY_KP_7)
        RegisterFlag(KEY_KP_8)
        RegisterFlag(KEY_KP_9)
        RegisterFlag(KEY_KP_DECIMAL)
        RegisterFlag(KEY_KP_DIVIDE)
        RegisterFlag(KEY_KP_MULTIPLY)
        RegisterFlag(KEY_KP_SUBTRACT)
        RegisterFlag(KEY_KP_ADD)
        RegisterFlag(KEY_KP_ENTER)
        RegisterFlag(KEY_KP_EQUAL)
        RegisterFlag(KEY_LEFT_SHIFT)
        RegisterFlag(KEY_LEFT_CONTROL)
        RegisterFlag(KEY_LEFT_ALT)
        RegisterFlag(KEY_LEFT_SUPER)
        RegisterFlag(KEY_RIGHT_SHIFT)
        RegisterFlag(KEY_RIGHT_CONTROL)
        RegisterFlag(KEY_RIGHT_ALT)
        RegisterFlag(KEY_RIGHT_SUPER)
        RegisterFlag(KEY_MENU)
        RegisterFlag(KEY_WINDOW_CLOSE)

        RegisterFlag(MOUSEBUTTON_0)
        RegisterFlag(MOUSEBUTTON_1)
        RegisterFlag(MOUSEBUTTON_2)
        RegisterFlag(MOUSEBUTTON_3)
        RegisterFlag(MOUSEBUTTON_4)

        RegisterFlag(MOUSE_LEFT)
        RegisterFlag(MOUSE_UP)
        RegisterFlag(MOUSE_RIGHT)
        RegisterFlag(MOUSE_DOWN)

        RegisterFlag(MOUSE_SCROLL_UP)
        RegisterFlag(MOUSE_SCROLL_DOWN)
        RegisterFlag(MOUSE_SCROLL_LEFT)
        RegisterFlag(MOUSE_SCROLL_RIGHT)

        RegisterFlag(GAMEPAD_A)
        RegisterFlag(GAMEPAD_B)
        RegisterFlag(GAMEPAD_X)
        RegisterFlag(GAMEPAD_Y)

        RegisterFlag(GAMEPAD_LB)
        RegisterFlag(GAMEPAD_RB)

        RegisterFlag(GAMEPAD_BACK)
        RegisterFlag(GAMEPAD_START)

        RegisterFlag(GAMEPAD_LS)
        RegisterFlag(GAMEPAD_RS)

        RegisterFlag(GAMEPAD_DPAD_UP)
        RegisterFlag(GAMEPAD_DPAD_RIGHT)
        RegisterFlag(GAMEPAD_DPAD_DOWN)
        RegisterFlag(GAMEPAD_DPAD_LEFT)

        RegisterFlag(GAMEPAD_LS_LEFT)
        RegisterFlag(GAMEPAD_LS_UP)
        RegisterFlag(GAMEPAD_LS_RIGHT)
        RegisterFlag(GAMEPAD_LS_DOWN)

        RegisterFlag(GAMEPAD_RS_LEFT)
        RegisterFlag(GAMEPAD_RS_UP)
        RegisterFlag(GAMEPAD_RS_RIGHT)
        RegisterFlag(GAMEPAD_RS_DOWN)

        RegisterFlag(GAMEPAD_RT)
        RegisterFlag(GAMEPAD_LT)

        RegisterFlag(GAMEPAD_1)
        RegisterFlag(GAMEPAD_2)
        RegisterFlag(GAMEPAD_3)
        RegisterFlag(GAMEPAD_4)
    EndEnum()
EndUnit()