//
// Created by Kim Johannsen on 31-03-2018.
//

#include <Core/Enum.h>
#include "Key.h"

DefineEnum(Key, false)
    DefineFlag(KEY_NONE)

    DefineFlag(KEY_SPACE)
    DefineFlag(KEY_APOSTROPHE)
    DefineFlag(KEY_COMMA)
    DefineFlag(KEY_MINUS)
    DefineFlag(KEY_PERIOD)
    DefineFlag(KEY_SLASH)
    DefineFlag(KEY_0)
    DefineFlag(KEY_1)
    DefineFlag(KEY_2)
    DefineFlag(KEY_3)
    DefineFlag(KEY_4)
    DefineFlag(KEY_5)
    DefineFlag(KEY_6)
    DefineFlag(KEY_7)
    DefineFlag(KEY_8)
    DefineFlag(KEY_9)
    DefineFlag(KEY_SEMICOLON)
    DefineFlag(KEY_EQUAL)
    DefineFlag(KEY_A)
    DefineFlag(KEY_B)
    DefineFlag(KEY_C)
    DefineFlag(KEY_D)
    DefineFlag(KEY_E)
    DefineFlag(KEY_F)
    DefineFlag(KEY_G)
    DefineFlag(KEY_H)
    DefineFlag(KEY_I)
    DefineFlag(KEY_J)
    DefineFlag(KEY_K)
    DefineFlag(KEY_L)
    DefineFlag(KEY_M)
    DefineFlag(KEY_N)
    DefineFlag(KEY_O)
    DefineFlag(KEY_P)
    DefineFlag(KEY_Q)
    DefineFlag(KEY_R)
    DefineFlag(KEY_S)
    DefineFlag(KEY_T)
    DefineFlag(KEY_U)
    DefineFlag(KEY_V)
    DefineFlag(KEY_W)
    DefineFlag(KEY_X)
    DefineFlag(KEY_Y)
    DefineFlag(KEY_Z)
    DefineFlag(KEY_LEFT_BRACKET)
    DefineFlag(KEY_BACKSLASH)
    DefineFlag(KEY_RIGHT_BRACKET)
    DefineFlag(KEY_GRAVE_ACCENT)
    DefineFlag(KEY_WORLD_1)
    DefineFlag(KEY_WORLD_2)
    DefineFlag(KEY_ESCAPE)
    DefineFlag(KEY_ENTER)
    DefineFlag(KEY_TAB)
    DefineFlag(KEY_BACKSPACE)
    DefineFlag(KEY_INSERT)
    DefineFlag(KEY_DELETE)
    DefineFlag(KEY_RIGHT)
    DefineFlag(KEY_LEFT)
    DefineFlag(KEY_DOWN)
    DefineFlag(KEY_UP)
    DefineFlag(KEY_PAGE_UP)
    DefineFlag(KEY_PAGE_DOWN)
    DefineFlag(KEY_HOME)
    DefineFlag(KEY_END)
    DefineFlag(KEY_CAPS_LOCK)
    DefineFlag(KEY_SCROLL_LOCK)
    DefineFlag(KEY_NUM_LOCK)
    DefineFlag(KEY_PRINT_SCREEN)
    DefineFlag(KEY_PAUSE)
    DefineFlag(KEY_F1)
    DefineFlag(KEY_F2)
    DefineFlag(KEY_F3)
    DefineFlag(KEY_F4)
    DefineFlag(KEY_F5)
    DefineFlag(KEY_F6)
    DefineFlag(KEY_F7)
    DefineFlag(KEY_F8)
    DefineFlag(KEY_F9)
    DefineFlag(KEY_F10)
    DefineFlag(KEY_F11)
    DefineFlag(KEY_F12)
    DefineFlag(KEY_F13)
    DefineFlag(KEY_F14)
    DefineFlag(KEY_F15)
    DefineFlag(KEY_F16)
    DefineFlag(KEY_F17)
    DefineFlag(KEY_F18)
    DefineFlag(KEY_F19)
    DefineFlag(KEY_F20)
    DefineFlag(KEY_F21)
    DefineFlag(KEY_F22)
    DefineFlag(KEY_F23)
    DefineFlag(KEY_F24)
    DefineFlag(KEY_F25)
    DefineFlag(KEY_KP_0)
    DefineFlag(KEY_KP_1)
    DefineFlag(KEY_KP_2)
    DefineFlag(KEY_KP_3)
    DefineFlag(KEY_KP_4)
    DefineFlag(KEY_KP_5)
    DefineFlag(KEY_KP_6)
    DefineFlag(KEY_KP_7)
    DefineFlag(KEY_KP_8)
    DefineFlag(KEY_KP_9)
    DefineFlag(KEY_KP_DECIMAL)
    DefineFlag(KEY_KP_DIVIDE)
    DefineFlag(KEY_KP_MULTIPLY)
    DefineFlag(KEY_KP_SUBTRACT)
    DefineFlag(KEY_KP_ADD)
    DefineFlag(KEY_KP_ENTER)
    DefineFlag(KEY_KP_EQUAL)
    DefineFlag(KEY_LEFT_SHIFT)
    DefineFlag(KEY_LEFT_CONTROL)
    DefineFlag(KEY_LEFT_ALT)
    DefineFlag(KEY_LEFT_SUPER)
    DefineFlag(KEY_RIGHT_SHIFT)
    DefineFlag(KEY_RIGHT_CONTROL)
    DefineFlag(KEY_RIGHT_ALT)
    DefineFlag(KEY_RIGHT_SUPER)
    DefineFlag(KEY_MENU)

    DefineFlag(MOUSEBUTTON_0)
    DefineFlag(MOUSEBUTTON_1)
    DefineFlag(MOUSEBUTTON_2)
    DefineFlag(MOUSEBUTTON_3)
    DefineFlag(MOUSEBUTTON_4)

    DefineFlag(MOUSE_LEFT)
    DefineFlag(MOUSE_UP)
    DefineFlag(MOUSE_RIGHT)
    DefineFlag(MOUSE_DOWN)

    DefineFlag(MOUSE_SCROLL_UP)
    DefineFlag(MOUSE_SCROLL_DOWN)
    DefineFlag(MOUSE_SCROLL_LEFT)
    DefineFlag(MOUSE_SCROLL_RIGHT)

    DefineFlag(GAMEPAD_A)
    DefineFlag(GAMEPAD_B)
    DefineFlag(GAMEPAD_X)
    DefineFlag(GAMEPAD_Y)

    DefineFlag(GAMEPAD_LB)
    DefineFlag(GAMEPAD_RB)

    DefineFlag(GAMEPAD_BACK)
    DefineFlag(GAMEPAD_START)

    DefineFlag(GAMEPAD_LS)
    DefineFlag(GAMEPAD_RS)

    DefineFlag(GAMEPAD_DPAD_UP)
    DefineFlag(GAMEPAD_DPAD_RIGHT)
    DefineFlag(GAMEPAD_DPAD_DOWN)
    DefineFlag(GAMEPAD_DPAD_LEFT)

    DefineFlag(GAMEPAD_LS_LEFT)
    DefineFlag(GAMEPAD_LS_UP)
    DefineFlag(GAMEPAD_LS_RIGHT)
    DefineFlag(GAMEPAD_LS_DOWN)

    DefineFlag(GAMEPAD_RS_LEFT)
    DefineFlag(GAMEPAD_RS_UP)
    DefineFlag(GAMEPAD_RS_RIGHT)
    DefineFlag(GAMEPAD_RS_DOWN)

    DefineFlag(GAMEPAD_RT)
    DefineFlag(GAMEPAD_LT)

    DefineFlag(GAMEPAD_1)
    DefineFlag(GAMEPAD_2)
    DefineFlag(GAMEPAD_3)
    DefineFlag(GAMEPAD_4)
EndEnum()