cv2pdb .\cmake-build-debug\Debugger.exe
cv2pdb .\cmake-build-debug\libCore.dll
cv2pdb .\cmake-build-debug\libFoundation.dll
cv2pdb .\cmake-build-debug\libRendering.dll
cv2pdb .\cmake-build-debug\libJson.dll
cv2pdb .\cmake-build-debug\libFile.dll
cv2pdb .\cmake-build-debug\libBgfxRendering.dll
cv2pdb .\cmake-build-debug\libDebug.dll
cv2pdb .\cmake-build-debug\libAnimation.dll
cv2pdb .\cmake-build-debug\libInput.dll
cv2pdb .\cmake-build-debug\libScene.dll
