//
// Created by Kim Johannsen on 30-03-2018.
//

#ifndef PLAZA_FIRSTPERSONCAMERA_H
#define PLAZA_FIRSTPERSONCAMERA_H

#include <Core/Service.h>

DeclareComponent(FirstPersonController)
DeclareComponentPropertyReactive(FirstPersonController, float, FirstPersonDamping)
DeclareComponentPropertyReactive(FirstPersonController, float, FirstPersonAcceleration)
DeclareComponentPropertyReactive(FirstPersonController, float, FirstPersonSpeed)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonActiveState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonForwardState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonBackState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonLeftState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonRightState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonUpState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonDownState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonLookLeftState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonLookRightState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonLookUpState)
DeclareComponentPropertyReactive(FirstPersonController, Entity, FirstPersonLookDownState)
DeclareComponentPropertyReactive(FirstPersonController, v3f, FirstPersonVelocity)

DeclareService(FirstPersonController)

#endif //PLAZA_FIRSTPERSONCAMERA_H
