# GNU Make project makefile autogenerated by GENie
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(MAKESHELL)))
  SHELLTYPE := posix
endif

ifeq (posix,$(SHELLTYPE))
  MKDIR = $(SILENT) mkdir -p "$(1)"
  COPY  = $(SILENT) cp -fR "$(1)" "$(2)"
  RM    = $(SILENT) rm -f "$(1)"
else
  MKDIR = $(SILENT) mkdir "$(subst /,\\,$(1))" 2> nul || exit 0
  COPY  = $(SILENT) copy /Y "$(subst /,\\,$(1))" "$(subst /,\\,$(2))"
  RM    = $(SILENT) del /F "$(subst /,\\,$(1))" 2> nul || exit 0
endif

CC  = gcc
CXX = g++
AR  = ar

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

MAKEFILE = bx.test.make

ifeq ($(config),debug32)
  OBJDIR              = ../../osx32_clang/obj/x32/Debug/bx.test
  TARGETDIR           = ../../osx32_clang/bin
  TARGET              = $(TARGETDIR)/bx.testDebug
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_DEBUG
  INCLUDES           += -I"../../../include/compat/osx" -I"../../../include" -I"../../../3rdparty"
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m32 -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m32 -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m32 -fno-rtti -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m32 -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m32 -fno-rtti -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L../../osx32_clang/bin -L. -m32
  LDDEPS             += ../../osx32_clang/bin/libbxDebug.a
  LIBS               += $(LDDEPS) -framework Cocoa
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/tests/atomic_test.o \
	$(OBJDIR)/tests/crt_test.o \
	$(OBJDIR)/tests/easing_test.o \
	$(OBJDIR)/tests/filepath_test.o \
	$(OBJDIR)/tests/handle_test.o \
	$(OBJDIR)/tests/hash_test.o \
	$(OBJDIR)/tests/macros_test.o \
	$(OBJDIR)/tests/main_test.o \
	$(OBJDIR)/tests/math_test.o \
	$(OBJDIR)/tests/os_test.o \
	$(OBJDIR)/tests/queue_test.o \
	$(OBJDIR)/tests/ringbuffer_test.o \
	$(OBJDIR)/tests/rng_test.o \
	$(OBJDIR)/tests/run_test.o \
	$(OBJDIR)/tests/settings_test.o \
	$(OBJDIR)/tests/simd_test.o \
	$(OBJDIR)/tests/sort_test.o \
	$(OBJDIR)/tests/string_test.o \
	$(OBJDIR)/tests/thread_test.o \
	$(OBJDIR)/tests/tokenizecmd_test.o \
	$(OBJDIR)/tests/uint32_test.o \
	$(OBJDIR)/tests/unordered_map_nonpod_test.o \
	$(OBJDIR)/tests/unordered_set_copyctor_test.o \
	$(OBJDIR)/tests/unordered_set_pod_test.o \
	$(OBJDIR)/tests/url_test.o \
	$(OBJDIR)/tests/vector_complex_test.o \
	$(OBJDIR)/tests/vector_header_test.o \
	$(OBJDIR)/tests/vector_nocopy_test.o \
	$(OBJDIR)/tests/vector_nodefault_test.o \
	$(OBJDIR)/tests/vector_primitive_test.o \
	$(OBJDIR)/tests/vector_shrinktofit_test.o \
	$(OBJDIR)/tests/vsnprintf_test.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR              = ../../osx32_clang/obj/x32/Release/bx.test
  TARGETDIR           = ../../osx32_clang/bin
  TARGET              = $(TARGETDIR)/bx.testRelease
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DNDEBUG
  INCLUDES           += -I"../../../include/compat/osx" -I"../../../include" -I"../../../3rdparty"
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m32 -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m32 -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m32 -fno-rtti -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m32 -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m32 -fno-rtti -Wshadow -m32 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L../../osx32_clang/bin -L. -m32
  LDDEPS             += ../../osx32_clang/bin/libbxRelease.a
  LIBS               += $(LDDEPS) -framework Cocoa
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/tests/atomic_test.o \
	$(OBJDIR)/tests/crt_test.o \
	$(OBJDIR)/tests/easing_test.o \
	$(OBJDIR)/tests/filepath_test.o \
	$(OBJDIR)/tests/handle_test.o \
	$(OBJDIR)/tests/hash_test.o \
	$(OBJDIR)/tests/macros_test.o \
	$(OBJDIR)/tests/main_test.o \
	$(OBJDIR)/tests/math_test.o \
	$(OBJDIR)/tests/os_test.o \
	$(OBJDIR)/tests/queue_test.o \
	$(OBJDIR)/tests/ringbuffer_test.o \
	$(OBJDIR)/tests/rng_test.o \
	$(OBJDIR)/tests/run_test.o \
	$(OBJDIR)/tests/settings_test.o \
	$(OBJDIR)/tests/simd_test.o \
	$(OBJDIR)/tests/sort_test.o \
	$(OBJDIR)/tests/string_test.o \
	$(OBJDIR)/tests/thread_test.o \
	$(OBJDIR)/tests/tokenizecmd_test.o \
	$(OBJDIR)/tests/uint32_test.o \
	$(OBJDIR)/tests/unordered_map_nonpod_test.o \
	$(OBJDIR)/tests/unordered_set_copyctor_test.o \
	$(OBJDIR)/tests/unordered_set_pod_test.o \
	$(OBJDIR)/tests/url_test.o \
	$(OBJDIR)/tests/vector_complex_test.o \
	$(OBJDIR)/tests/vector_header_test.o \
	$(OBJDIR)/tests/vector_nocopy_test.o \
	$(OBJDIR)/tests/vector_nodefault_test.o \
	$(OBJDIR)/tests/vector_primitive_test.o \
	$(OBJDIR)/tests/vector_shrinktofit_test.o \
	$(OBJDIR)/tests/vsnprintf_test.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR              = ../../osx64_clang/obj/x64/Debug/bx.test
  TARGETDIR           = ../../osx64_clang/bin
  TARGET              = $(TARGETDIR)/bx.testDebug
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_DEBUG
  INCLUDES           += -I"../../../include/compat/osx" -I"../../../include" -I"../../../3rdparty"
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m64 -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m64 -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m64 -fno-rtti -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m64 -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -m64 -fno-rtti -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L../../osx64_clang/bin -L. -m64
  LDDEPS             += ../../osx64_clang/bin/libbxDebug.a
  LIBS               += $(LDDEPS) -framework Cocoa
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/tests/atomic_test.o \
	$(OBJDIR)/tests/crt_test.o \
	$(OBJDIR)/tests/easing_test.o \
	$(OBJDIR)/tests/filepath_test.o \
	$(OBJDIR)/tests/handle_test.o \
	$(OBJDIR)/tests/hash_test.o \
	$(OBJDIR)/tests/macros_test.o \
	$(OBJDIR)/tests/main_test.o \
	$(OBJDIR)/tests/math_test.o \
	$(OBJDIR)/tests/os_test.o \
	$(OBJDIR)/tests/queue_test.o \
	$(OBJDIR)/tests/ringbuffer_test.o \
	$(OBJDIR)/tests/rng_test.o \
	$(OBJDIR)/tests/run_test.o \
	$(OBJDIR)/tests/settings_test.o \
	$(OBJDIR)/tests/simd_test.o \
	$(OBJDIR)/tests/sort_test.o \
	$(OBJDIR)/tests/string_test.o \
	$(OBJDIR)/tests/thread_test.o \
	$(OBJDIR)/tests/tokenizecmd_test.o \
	$(OBJDIR)/tests/uint32_test.o \
	$(OBJDIR)/tests/unordered_map_nonpod_test.o \
	$(OBJDIR)/tests/unordered_set_copyctor_test.o \
	$(OBJDIR)/tests/unordered_set_pod_test.o \
	$(OBJDIR)/tests/url_test.o \
	$(OBJDIR)/tests/vector_complex_test.o \
	$(OBJDIR)/tests/vector_header_test.o \
	$(OBJDIR)/tests/vector_nocopy_test.o \
	$(OBJDIR)/tests/vector_nodefault_test.o \
	$(OBJDIR)/tests/vector_primitive_test.o \
	$(OBJDIR)/tests/vector_shrinktofit_test.o \
	$(OBJDIR)/tests/vsnprintf_test.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR              = ../../osx64_clang/obj/x64/Release/bx.test
  TARGETDIR           = ../../osx64_clang/bin
  TARGET              = $(TARGETDIR)/bx.testRelease
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DNDEBUG
  INCLUDES           += -I"../../../include/compat/osx" -I"../../../include" -I"../../../3rdparty"
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m64 -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m64 -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m64 -fno-rtti -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m64 -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -m64 -fno-rtti -Wshadow -m64 -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L../../osx64_clang/bin -L. -m64
  LDDEPS             += ../../osx64_clang/bin/libbxRelease.a
  LIBS               += $(LDDEPS) -framework Cocoa
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/tests/atomic_test.o \
	$(OBJDIR)/tests/crt_test.o \
	$(OBJDIR)/tests/easing_test.o \
	$(OBJDIR)/tests/filepath_test.o \
	$(OBJDIR)/tests/handle_test.o \
	$(OBJDIR)/tests/hash_test.o \
	$(OBJDIR)/tests/macros_test.o \
	$(OBJDIR)/tests/main_test.o \
	$(OBJDIR)/tests/math_test.o \
	$(OBJDIR)/tests/os_test.o \
	$(OBJDIR)/tests/queue_test.o \
	$(OBJDIR)/tests/ringbuffer_test.o \
	$(OBJDIR)/tests/rng_test.o \
	$(OBJDIR)/tests/run_test.o \
	$(OBJDIR)/tests/settings_test.o \
	$(OBJDIR)/tests/simd_test.o \
	$(OBJDIR)/tests/sort_test.o \
	$(OBJDIR)/tests/string_test.o \
	$(OBJDIR)/tests/thread_test.o \
	$(OBJDIR)/tests/tokenizecmd_test.o \
	$(OBJDIR)/tests/uint32_test.o \
	$(OBJDIR)/tests/unordered_map_nonpod_test.o \
	$(OBJDIR)/tests/unordered_set_copyctor_test.o \
	$(OBJDIR)/tests/unordered_set_pod_test.o \
	$(OBJDIR)/tests/url_test.o \
	$(OBJDIR)/tests/vector_complex_test.o \
	$(OBJDIR)/tests/vector_header_test.o \
	$(OBJDIR)/tests/vector_nocopy_test.o \
	$(OBJDIR)/tests/vector_nodefault_test.o \
	$(OBJDIR)/tests/vector_primitive_test.o \
	$(OBJDIR)/tests/vector_shrinktofit_test.o \
	$(OBJDIR)/tests/vsnprintf_test.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug)
  OBJDIR              = obj/Debug/bx.test
  TARGETDIR           = ../../../scripts
  TARGET              = $(TARGETDIR)/bx.testDebug
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_DEBUG
  INCLUDES           += -I"../../../include/compat/osx" -I"../../../include" -I"../../../3rdparty"
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -fno-rtti -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -fno-rtti -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L../../../scripts -L.
  LDDEPS             += ../../../scripts/libbxDebug.a
  LIBS               += $(LDDEPS) -framework Cocoa
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/tests/atomic_test.o \
	$(OBJDIR)/tests/crt_test.o \
	$(OBJDIR)/tests/easing_test.o \
	$(OBJDIR)/tests/filepath_test.o \
	$(OBJDIR)/tests/handle_test.o \
	$(OBJDIR)/tests/hash_test.o \
	$(OBJDIR)/tests/macros_test.o \
	$(OBJDIR)/tests/main_test.o \
	$(OBJDIR)/tests/math_test.o \
	$(OBJDIR)/tests/os_test.o \
	$(OBJDIR)/tests/queue_test.o \
	$(OBJDIR)/tests/ringbuffer_test.o \
	$(OBJDIR)/tests/rng_test.o \
	$(OBJDIR)/tests/run_test.o \
	$(OBJDIR)/tests/settings_test.o \
	$(OBJDIR)/tests/simd_test.o \
	$(OBJDIR)/tests/sort_test.o \
	$(OBJDIR)/tests/string_test.o \
	$(OBJDIR)/tests/thread_test.o \
	$(OBJDIR)/tests/tokenizecmd_test.o \
	$(OBJDIR)/tests/uint32_test.o \
	$(OBJDIR)/tests/unordered_map_nonpod_test.o \
	$(OBJDIR)/tests/unordered_set_copyctor_test.o \
	$(OBJDIR)/tests/unordered_set_pod_test.o \
	$(OBJDIR)/tests/url_test.o \
	$(OBJDIR)/tests/vector_complex_test.o \
	$(OBJDIR)/tests/vector_header_test.o \
	$(OBJDIR)/tests/vector_nocopy_test.o \
	$(OBJDIR)/tests/vector_nodefault_test.o \
	$(OBJDIR)/tests/vector_primitive_test.o \
	$(OBJDIR)/tests/vector_shrinktofit_test.o \
	$(OBJDIR)/tests/vsnprintf_test.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR              = obj/Release/bx.test
  TARGETDIR           = ../../../scripts
  TARGET              = $(TARGETDIR)/bx.testRelease
  DEFINES            += -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -DNDEBUG
  INCLUDES           += -I"../../../include/compat/osx" -I"../../../include" -I"../../../3rdparty"
  INCLUDES           +=
  ALL_CPPFLAGS       += $(CPPFLAGS) -MMD -MP -MP $(DEFINES) $(INCLUDES)
  ALL_ASMFLAGS       += $(ASMFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CFLAGS         += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_CXXFLAGS       += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -fno-rtti -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_OBJCFLAGS      += $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef
  ALL_OBJCPPFLAGS    += $(CXXFLAGS) $(CFLAGS) $(ALL_CPPFLAGS) $(ARCH) -Wall -Wextra -fomit-frame-pointer -g -O3 -fno-rtti -Wshadow -Wfatal-errors -msse2 -Wunused-value -Wundef -std=c++11
  ALL_RESFLAGS       += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  ALL_LDFLAGS        += $(LDFLAGS) -L../../../scripts -L.
  LDDEPS             += ../../../scripts/libbxRelease.a
  LIBS               += $(LDDEPS) -framework Cocoa
  EXTERNAL_LIBS      +=
  LINKCMD             = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(ALL_LDFLAGS) $(LIBS)
  OBJECTS := \
	$(OBJDIR)/tests/atomic_test.o \
	$(OBJDIR)/tests/crt_test.o \
	$(OBJDIR)/tests/easing_test.o \
	$(OBJDIR)/tests/filepath_test.o \
	$(OBJDIR)/tests/handle_test.o \
	$(OBJDIR)/tests/hash_test.o \
	$(OBJDIR)/tests/macros_test.o \
	$(OBJDIR)/tests/main_test.o \
	$(OBJDIR)/tests/math_test.o \
	$(OBJDIR)/tests/os_test.o \
	$(OBJDIR)/tests/queue_test.o \
	$(OBJDIR)/tests/ringbuffer_test.o \
	$(OBJDIR)/tests/rng_test.o \
	$(OBJDIR)/tests/run_test.o \
	$(OBJDIR)/tests/settings_test.o \
	$(OBJDIR)/tests/simd_test.o \
	$(OBJDIR)/tests/sort_test.o \
	$(OBJDIR)/tests/string_test.o \
	$(OBJDIR)/tests/thread_test.o \
	$(OBJDIR)/tests/tokenizecmd_test.o \
	$(OBJDIR)/tests/uint32_test.o \
	$(OBJDIR)/tests/unordered_map_nonpod_test.o \
	$(OBJDIR)/tests/unordered_set_copyctor_test.o \
	$(OBJDIR)/tests/unordered_set_pod_test.o \
	$(OBJDIR)/tests/url_test.o \
	$(OBJDIR)/tests/vector_complex_test.o \
	$(OBJDIR)/tests/vector_header_test.o \
	$(OBJDIR)/tests/vector_nocopy_test.o \
	$(OBJDIR)/tests/vector_nodefault_test.o \
	$(OBJDIR)/tests/vector_primitive_test.o \
	$(OBJDIR)/tests/vector_shrinktofit_test.o \
	$(OBJDIR)/tests/vsnprintf_test.o \

  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJDIRS := \
	$(OBJDIR) \
	$(OBJDIR)/tests \

RESOURCES := \

.PHONY: clean prebuild prelink

all: $(OBJDIRS) $(TARGETDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(EXTERNAL_LIBS) $(RESOURCES) | $(TARGETDIR) $(OBJDIRS)
	@echo Linking bx.test
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	-$(call MKDIR,$(TARGETDIR))

$(OBJDIRS):
	@echo Creating $(@)
	-$(call MKDIR,$@)

clean:
	@echo Cleaning bx.test
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) -x c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"

$(GCH_OBJC): $(PCH) $(MAKEFILE) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_OBJCPPFLAGS) -x objective-c++-header $(DEFINES) $(INCLUDES) -o "$@" -c "$<"
endif

$(OBJDIR)/tests/atomic_test.o: ../../../tests/atomic_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/crt_test.o: ../../../tests/crt_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/easing_test.o: ../../../tests/easing_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/filepath_test.o: ../../../tests/filepath_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/handle_test.o: ../../../tests/handle_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/hash_test.o: ../../../tests/hash_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/macros_test.o: ../../../tests/macros_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/main_test.o: ../../../tests/main_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/math_test.o: ../../../tests/math_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/os_test.o: ../../../tests/os_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/queue_test.o: ../../../tests/queue_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/ringbuffer_test.o: ../../../tests/ringbuffer_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/rng_test.o: ../../../tests/rng_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/run_test.o: ../../../tests/run_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/settings_test.o: ../../../tests/settings_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/simd_test.o: ../../../tests/simd_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/sort_test.o: ../../../tests/sort_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/string_test.o: ../../../tests/string_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/thread_test.o: ../../../tests/thread_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/tokenizecmd_test.o: ../../../tests/tokenizecmd_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/uint32_test.o: ../../../tests/uint32_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/unordered_map_nonpod_test.o: ../../../tests/unordered_map_nonpod_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/unordered_set_copyctor_test.o: ../../../tests/unordered_set_copyctor_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/unordered_set_pod_test.o: ../../../tests/unordered_set_pod_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/url_test.o: ../../../tests/url_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/vector_complex_test.o: ../../../tests/vector_complex_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/vector_header_test.o: ../../../tests/vector_header_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/vector_nocopy_test.o: ../../../tests/vector_nocopy_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/vector_nodefault_test.o: ../../../tests/vector_nodefault_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/vector_primitive_test.o: ../../../tests/vector_primitive_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/vector_shrinktofit_test.o: ../../../tests/vector_shrinktofit_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

$(OBJDIR)/tests/vsnprintf_test.o: ../../../tests/vsnprintf_test.cpp $(GCH) $(MAKEFILE)
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
  -include $(OBJDIR)/$(notdir $(PCH))_objc.d
endif
